### ISSUE TITLE
dependency missing for docker-compose

### ISSUE THREAD

**Issue by tim-m-robinson** [gatblau/europa#4]
the latest dev build has broken docker-compose:

[europa@localhost]$ docker-compose up
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 3011, in <module>
    parse_requirements(**requires**), Environment()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: backports.ssl-match-hostname>=3.5

Solution is:

> sudo pip install backports.ssl_match_hostname --upgrade

**Comment by gatblau** [comment]
this issue has been resolved in v1.1.0
